services:
  web:
    build: .
    env_file:
      - .project.env/.env
    ports:
      - 8000:8000
    command: >
      poetry run python app/manage.py runserver 0.0.0.0:8000
    tty: true
    volumes:
      - ./app:/opt/app
  postgres:
    image: postgres:17
    env_file:
      - .project.env/postgres.env
    ports:
      - 5440:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: